# Generated by Django 4.0 on 2022-04-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='price',
            new_name='_price',
        ),
    ]
